### ISSUE TITLE
"RuntimeException: Unable to create service" when connecting bluetooth mic

### ISSUE THREAD

**Issue by ghtesting2020** [mollyim/mollyim-android#162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Since the latest version I have a screen pop up on my home screen saying "Molly keeps stopping" every 7 or 8 hours this happens despite Molly not even being open in the backgroubd. I did full restart but no help. Is there a new scheduled service or something that runs every 7 or 8 hours?

I'm running latest grapheneos which is android 13.

![Crash](https://user-images.githubusercontent.com/69682350/214472195-71dbfb1f-58c7-4fa4-9b9e-f0a467c74f7a.png)

```
type: crash
package: im.molly.app:119600
process: im.molly.app
processUptime: 205 + 273 ms

java.lang.RuntimeException: Unable to create service org.thoughtcrime.securesms.components.voice.VoiceNotePlaybackService: java.lang.IllegalStateException
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4504)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2162)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7878)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.IllegalStateException
	at org.thoughtcrime.securesms.service.KeyCachingService.getMasterSecret(KeyCachingService.java:87)
	at org.thoughtcrime.securesms.crypto.EncryptedPreferences.getCipher(EncryptedPreferences.java:448)
	at org.thoughtcrime.securesms.crypto.EncryptedPreferences.getDecryptedObject(EncryptedPreferences.java:373)
	at org.thoughtcrime.securesms.crypto.EncryptedPreferences.getInt(EncryptedPreferences.java:276)
	at org.thoughtcrime.securesms.util.TextSecurePreferences.getIntegerPreference(TextSecurePreferences.java:1064)
	at org.thoughtcrime.securesms.util.TextSecurePreferences.getNotificationChannelVersion(TextSecurePreferences.java:955)
	at org.thoughtcrime.securesms.notifications.NotificationChannels.<init>(NotificationChannels.java:111)
	at org.thoughtcrime.securesms.notifications.NotificationChannels.getInstance(NotificationChannels.java:90)
	at org.thoughtcrime.securesms.components.voice.VoiceNoteNotificationManager.<init>(VoiceNoteNotificationManager.java:43)
	at org.thoughtcrime.securesms.components.voice.VoiceNotePlaybackService.onCreate(VoiceNotePlaybackService.java:85)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4491)
	... 11 more
```

### Steps to reproduce

1. Update to newest version
2. Wait 7 or 8 hours

### Molly version

Version v6.8.3-1-FOSS

**Comment by valldrac** [comment]
I fixed the bug but I'm not sure about the root cause.

Have you installed any 3rd party app to control media playback? Or have you had any problem lately playing voice notes in Molly?
