### ISSUE TITLE
App crash at startup

### ISSUE THREAD

**Issue by robin-161** [mollyim/mollyim-android#174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Molly crashed after unlocking the database with an "not responding" popup. Launching Molly while internet connection is off works fine.

### Steps to reproduce

1. Open Molly
2. Unlock database
3. "Not responding" popup shows

### Molly version

v6.14.5-1-FOSS

### Android version

Android 13

### Device

Google Pixel 6

**Comment by Robert-litts** [comment]
I am also having the same issue with the same version of Molly. When I open Molly and go to unlock the database, I am sometimes sent into a cycle of "Not responding". 

Here is the crash log that I captured for my most recent event:

````
type: crash
osVersion: google/oriole/oriole:13/TQ2A.230305.008.E1/2023032000:user/release-keys
package: im.molly.app:123200
process: im.molly.app
processUptime: 637 + 741 ms

java.lang.RuntimeException: Unable to start service org.thoughtcrime.securesms.service.KeyCachingService@6259d5a with Intent { cmp=im.molly.app/org.thoughtcrime.securesms.service.KeyCachingService }: java.lang.IllegalStateException
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4677)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2177)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7891)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.IllegalStateException
	at org.thoughtcrime.securesms.service.KeyCachingService.getMasterSecret(KeyCachingService.java:87)
	at org.thoughtcrime.securesms.crypto.EncryptedPreferences.getCipher(EncryptedPreferences.java:448)
	at org.thoughtcrime.securesms.crypto.EncryptedPreferences.getDecryptedObject(EncryptedPreferences.java:373)
	at org.thoughtcrime.securesms.crypto.EncryptedPreferences.getInt(EncryptedPreferences.java:276)
	at org.thoughtcrime.securesms.util.TextSecurePreferences.getIntegerPreference(TextSecurePreferences.java:1062)
	at org.thoughtcrime.securesms.util.TextSecurePreferences.getNotificationChannelVersion(TextSecurePreferences.java:953)
	at org.thoughtcrime.securesms.notifications.NotificationChannels.<init>(NotificationChannels.java:113)
	at org.thoughtcrime.securesms.notifications.NotificationChannels.getInstance(NotificationChannels.java:92)
	at org.thoughtcrime.securesms.service.KeyCachingService.foregroundService(KeyCachingService.java:237)
	at org.thoughtcrime.securesms.service.KeyCachingService.handleCacheKey(KeyCachingService.java:155)
	at org.thoughtcrime.securesms.service.KeyCachingService.onStartCommand(KeyCachingService.java:118)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4659)
	... 11 more

````
