### ISSUE TITLE
After update molly from 5.52 to 6.25 it would crash+when trying to start from scratch and resoring backup Molly either crashes or wont be able to register the number that is given

### ISSUE THREAD

**Issue by natur960** [mollyim/mollyim-android#209]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I've agreed to update Molly. 
it wont operate after that just crashes. 

so iv'e tried installing from scrach and restoring the backup.  then it would keep crashing everytime after 2-3 seconds in the screen of re-registering the number . 

I've tried installing lower versions back like 5.52 , the resore would work but the register number screen would say there is a problem with the network. - when trying reregistering the number without restore it would work. 

when looking at the debug code it would say there is a databasecorrupted error (would attach later)

### Steps to reproduce

1. backup on 5.52 version
2. restore on 6.25 or higher
3. get to register number screen

### Molly version

6.25

### Android version

12

**Comment by natur960** [comment]
package: im.molly.app:128300
process: im.molly.app
processUptime: 8697 + 719 ms

org.thoughtcrime.securesms.database.SqlCipherErrorHandler$DatabaseCorruptedError_BothChecksPass
 at org.thoughtcrime.securesms.database.SqlCipherErrorHandler.onCorruption(SqlCipherErrorHandler.kt:39)
 at net.zetetic.database.sqlcipher.SQLiteDatabase.onCorruption(SQLiteDatabase.java:348)
 at net.zetetic.database.sqlcipher.SQLiteProgram.onCorruption(SQLiteProgram.java:117)
 at net.zetetic.database.sqlcipher.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:74)
 at net.zetetic.database.sqlcipher.SQLiteDatabase.executeSql(SQLiteDatabase.java:1993)
 at net.zetetic.database.sqlcipher.SQLiteDatabase.execSQL(SQLiteDatabase.java:1900)
 at org.thoughtcrime.securesms.database.helpers.migration.V191_UniqueMessageMigrationV2.migrate(V191_UniqueMessageMigrationV2.kt:43)
 at org.thoughtcrime.securesms.database.helpers.SignalDatabaseMigrations.migrate(SignalDatabaseMigrations.kt:238)
 at org.thoughtcrime.securesms.database.SignalDatabase.onUpgrade(SignalDatabase.kt:152)
 at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:403)
 at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:302)
 at org.thoughtcrime.securesms.database.SignalDatabase.getRawReadableDatabase(SignalDatabase.kt:177)
 at org.thoughtcrime.securesms.database.SignalDatabase$Companion.hasTable(SignalDatabase.kt:293)
 at org.thoughtcrime.securesms.database.SignalDatabase.hasTable(Unknown Source:2)
 at org.thoughtcrime.securesms.database.KeyValueDatabase.lambda$onOpen$0(KeyValueDatabase.java:99)
 at org.thoughtcrime.securesms.database.KeyValueDatabase.$r8$lambda$jefACyoHK4h3lvPI5zn7iBuWxuI(Unknown Source:0)
 at org.thoughtcrime.securesms.database.KeyValueDatabase$$ExternalSyntheticLambda0.run(Unknown Source:0)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
 at java.lang.Thread.run(Thread.java:1012)
 at org.signal.core.util.concurrent.SignalExecutors$NumberedThreadFactory$1.run(SignalExecutors.java:109)
 at [[ ↑↑ Original Trace ↑↑ ]].(:0)
 at [[ ↓↓ Inferred Trace ↓↓ ]].(:0)
 at Database 'signal.db' corrupted!.(:0)
 at [sqlite] FullCode: 267 | ErrorCode: 11 | ExtendedErrorCode: 1 | Message: database disk image is malformed | ExtraMessage: null.(:0)
 at Diagnostics [results:.(:0)](results:.%28:0%29)
 at  ===== PRAGMA integrity_check (same-connection) =====.(:0)
 at ok.(:0)
 at .(:0)
 at ===== PRAGMA cipher_integrity_check (same-connection) =====.(:0)
 at .(:0)
 at [[ ↑↑ Original Trace ↑↑ ]].(:0)
 at [[ ↓↓ Exception Message ↓↓ ]].(:0)
 at null.(:0)

**Comment by valldrac** [comment]
Same issue https://github.com/signalapp/Signal-Android/issues/13034

**Comment by ichthyosaurus** [comment]
There is a workaround now: https://github.com/signalapp/Signal-Android/issues/13034#issuecomment-1999685726

**Comment by s23-leng** [comment]
The [upstream issue](https://github.com/signalapp/Signal-Android/issues/13034) has been closed for a while now. @natur960, have You experienced this again?
