### ISSUE TITLE
Can't Create Backup Anymore

### ISSUE THREAD

**Issue by t-aus-m** [mollyim/mollyim-android#354]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Since monday my phone is unable to create backups of molly. The back up fails after a few seconds.

ADB shows the following noticable events:
```
07-25 13:41:52.573 32128 32173 D FullBackupExporter: Exporting table: story_sends
07-25 13:41:52.790 32128 32173 W LocalBackupJobApi29: Error during backup!
07-25 13:41:52.790 32128 32173 W LocalBackupJobApi29: java.io.IOException: Size mismatch!
07-25 13:41:52.790 32128 32173 W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.backup.BackupFrameOutputStream.write(BackupFrameOutputStream.java:114)
07-25 13:41:52.790 32128 32173 W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.backup.FullBackupExporter.internalExport(FullBackupExporter.java:199)
07-25 13:41:52.790 32128 32173 W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.backup.FullBackupExporter.export(FullBackupExporter.java:123)
07-25 13:41:52.790 32128 32173 W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.jobs.LocalBackupJobApi29.onRun(LocalBackupJobApi29.java:143)
07-25 13:41:52.790 32128 32173 W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:31)
07-25 13:41:52.790 32128 32173 W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
07-25 13:41:52.790 32128 32173 W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
```

### Steps to reproduce

1. Open Backup settings
2. Start Backup
3. Wait for it to fail

### Molly version

v7.8.1-2.up1-FOSS

### Android version

Android 14

### Device

Fairphone 5

### Link to debug log

https://debuglogs.org/android/7.8.1/ee877882d6c829c670ccaadbc3fdfc93c298ff5fa93b921e23872d262c359d5a

**Comment by valldrac** [comment]
It looks like a corrupted attachment is messing up the backup. To fix this, delete the broken attachment: go to Settings > Data and Storage > Manage Storage > Review Storage, and look for a file with a black thumbnail or one that won’t open. Once you delete it, the backup should work again.

**Comment by t-aus-m** [comment]
How can I find out which file causes the backup to fail? I deleted a bunch of corrupted files from the backup, but since I have over 2 GB of media, it would take a lot of time to go through all of the files.

**Comment by t-aus-m** [comment]
I wanted to revive this topic since the issue still persists for me: I now have gone through all of my media attachments and checked each and every one of them. There are only working attachments left, however the backup still won't finish with the same error …

**Comment by t-aus-m** [comment]
I have a set of more current logs here: https://debuglogs.org/android/7.23.1/7d3d3c72b63bcd7c56ca7b2d111f05eb777ad2ec31776bdb53b93b94ecd1c600

The issue seems to be still the same

**Comment by FamilyCloudDev** [comment]
This is also a issue for me. I have even tried deleting all attachments and files and it still fails everytime. This is on version version v7.49.1-1-FOSS

**Comment by trlef19** [comment]
Happens to me too

**Comment by valldrac** [comment]
This is a very old issue that has already been fixed in recent versions. We'll need more details about your setup (app version, debug log, etc.) to investigate properly.

Please open a new ticket with that information so we can take a look.
