### ISSUE TITLE
Logs to troubleshoot Molly <-> UnifiedPush distributor connection

### ISSUE THREAD

**Issue by pcrockett** [mollyim/mollyim-android#408]
### Is there an existing request for this?

- [X] I have searched the existing issues

### Feature description

When setting up UnifiedPush with Molly-FOSS I am finding that no new UP topic is being created in the `ntfy.sh` app. I _suspect_ that it's not a Molly-FOSS problem, but rather an OS problem (because I've wrestled with jankiness issues in [this operating system](https://e.foundation/e-os/) before).

Is it possible to see log output when Molly creates (or fails to create) a UP topic? I'm not seeing anything about this in the diagnostic logs after going through the UP setup flow.

**Comment by valldrac** [comment]
Why not share the log with us? We can check it for the error and add any necessary logging. You can paste it here (the log is redacted of personal information) or send it to support@molly.im.

You'll find the log in app's Settings > Help > Debug Log. Capture it after trying to setup UP.

**Comment by pcrockett** [comment]
If I remember correctly (I don't have the device in question at the moment) there's literally nothing of value in the logs. No indication that anything is happening at all. The logs look identical both before and after setting up unified push notifications.

**Comment by valldrac** [comment]
It might be a different issue. Do you have debug logs turned off in Molly? Was the device connected to the Internet when you changed the notification provider setting in Molly?

At the very least, you should see strings like `UnifiedPushRefreshJob` and `UnifiedPushReceiver` in the log.

**Comment by pcrockett** [comment]
Aha, you're right. I finally got around to troubleshooting again, and here's what I get in the logs:

```
12-13 21:31:51.149  3657  3657 I ApplicationContext: Switching to UnifiedPush.
12-13 21:31:51.262  3657  3905 I Job     : [JOB::f43488ed-7d2b-40dd-b5b7-776913189cfb][UnifiedPushRefreshJob] onSubmit() (Time Since Submission: 3 ms, Lifespan: 21600000 ms, Run Attempt: 1/3, Queue: FcmRefreshJob)
12-13 21:31:51.262  3657  3934 I JobSchedulerScheduler: JobScheduler enqueue of NETWORK (-1733499378)
12-13 21:31:51.263  3657  4078 I JobRunner: [JOB::f43488ed-7d2b-40dd-b5b7-776913189cfb][UnifiedPushRefreshJob][4] Running job. (Time Since Submission: 2 ms, Lifespan: 21600000 ms, Run Attempt: 1/3, Queue: FcmRefreshJob)
12-13 21:31:51.266  3657  4078 D UnifiedPushRefreshJob: Current registration status: PENDING
12-13 21:31:51.266  3657  4078 D UnifiedPushRefreshJob: Last notification received at: 0
12-13 21:31:51.277  3657  3657 W IncomingMessageObserver: Termination Enqueued! 69638201
12-13 21:31:51.277  3657  3657 W IncomingMessageObserver: java.lang.Throwable
12-13 21:31:51.277  3657  3657 W IncomingMessageObserver: 	at org.thoughtcrime.securesms.messages.IncomingMessageObserver.terminateAsync(IncomingMessageObserver.kt:224)
12-13 21:31:51.277  3657  3657 W IncomingMessageObserver: 	at org.thoughtcrime.securesms.dependencies.NetworkDependenciesModule.closeConnections(NetworkDependenciesModule.kt:187)
12-13 21:31:51.277  3657  3657 W IncomingMessageObserver: 	at org.thoughtcrime.securesms.dependencies.AppDependencies.resetNetwork(AppDependencies.kt:327)
12-13 21:31:51.277  3657  3657 W IncomingMessageObserver: 	at org.thoughtcrime.securesms.components.settings.app.notifications.NotificationsSettingsViewModel.setPreferredNotificationMethod(NotificationsSettingsViewModel.kt:120)
12-13 21:31:51.277  3657  3657 W IncomingMessageObserver: 	at org.thoughtcrime.securesms.components.settings.app.notifications.NotificationsSettingsFragment.qrScanLauncher$lambda$1(NotificationsSettingsFragment.kt:104)
12-13 21:31:51.277  3657  3657 W IncomingMessageObserver: 	at org.thoughtcrime.securesms.components.settings.app.notifications.NotificationsSettingsFragment.$r8$lambda$PlgIRBs33XJ2tbyiOXw0CDnJSE0(NotificationsSettingsFragment.kt:0)
12-13 21:31:51.277  3657  3657 W IncomingMessageObserver: 	at org.thoughtcrime.securesms.components.settings.app.notifications.NotificationsSettingsFragment$$ExternalSyntheticLambda3.onActivityResult(R8$$SyntheticClass:0)
12-13 21:31:51.277  3657  3657 W IncomingMessageObserver: 	at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.kt:371)
12-13 21:31:51.277  3657  3657 W IncomingMessageObserver: 	at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.kt:331)
12-13 21:31:51.277  3657  3657 W IncomingMessageObserver: 	at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.kt:786)
12-13 21:31:51.277  3657  3657 W IncomingMessageObserver: 	at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:151)
12-13 21:31:51.277  3657  3657 W IncomingMessageObserver: 	at org.thoughtcrime.securesms.components.settings.app.AppSettingsActivity.onActivityResult(AppSettingsActivity.kt:136)
12-13 21:31:51.277  3657  3657 W IncomingMessageObserver: 	at android.app.Activity.dispatchActivityResult(Activity.java:8665)
12-13 21:31:51.277  3657  3657 W IncomingMessageObserver: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5332)
12-13 21:31:51.277  3657  3657 W IncomingMessageObserver: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5378)
12-13 21:31:51.277  3657  3657 W IncomingMessageObserver: 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
12-13 21:31:51.277  3657  3657 W IncomingMessageObserver: 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
12-13 21:31:51.277  3657  3657 W IncomingMessageObserver: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
12-13 21:31:51.277  3657  3657 W IncomingMessageObserver: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
12-13 21:31:51.277  3657  3657 W IncomingMessageObserver: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
12-13 21:31:51.277  3657  3657 W IncomingMessageObserver: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-13 21:31:51.277  3657  3657 W IncomingMessageObserver: 	at android.os.Looper.loopOnce(Looper.java:201)
12-13 21:31:51.277  3657  3657 W IncomingMessageObserver: 	at android.os.Looper.loop(Looper.java:288)
12-13 21:31:51.277  3657  3657 W IncomingMessageObserver: 	at android.app.ActivityThread.main(ActivityThread.java:7924)
12-13 21:31:51.277  3657  3657 W IncomingMessageObserver: 	at java.lang.reflect.Method.invoke(Native Method)
12-13 21:31:51.277  3657  3657 W IncomingMessageObserver: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
12-13 21:31:51.277  3657  3657 W IncomingMessageObserver: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
12-13 21:31:51.278  3657  3657 W PushServiceSocket: Canceling: 5
12-13 21:31:51.278  3657  3657 W PushServiceSocket: Canceling: o...@...
12-13 21:31:51.279  3657  3657 W PushServiceSocket: Canceling: o...@...
12-13 21:31:51.279  3657  3657 W PushServiceSocket: Canceling: o...@...
12-13 21:31:51.279  3657  3657 W PushServiceSocket: Canceling: o...@...
12-13 21:31:51.279  3657  3657 W PushServiceSocket: Canceling: o...@...
```

Any ideas?

**Comment by valldrac** [comment]
I see the job to activate UnifiedPush started to run, but I’m missing more log lines after to see how it finished or if it throw any errors. The `IncomingMessageObserver: Termination Enqueued!` exception is normal and expected.

**Comment by pcrockett** [comment]
Ah ok, I think I underestimated how much logging is being done and I just didn't read far enough down.

The logs helped me figure out that there are two distributor apps installed -- the janky OS's fork of ntfy, and then the normal ntfy app. I switched which ntfy app it was using, and then everything started working.

So... we're good on logging then. Thanks for your help.
